# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Smart Campus Energy Lab
email: scel@hawaii.edu
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://scel-hawaii.org" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  scel-hawaii

# Build settings
markdown: kramdown

# Data Page
page_gen:
    - data: "members"
      template: "profile"
      name: "name"
      dir: "people"
